### ISSUE TITLE
Pytorch version

### ISSUE THREAD

**Issue by rst1991** [MingxuanXia/SEAL#1]
Please share the information of the pytorch version as I am not bale to replicate the results.

**Comment by MingxuanXia** [comment]
The Pytorch version we use is 1.13.1

**Comment by rst1991** [comment]
![seal](https://github.com/user-attachments/assets/c5bb6b9e-884a-4f50-bfee-87ef6978ebbc)
This is the result of C--> A for Office home dataset. The paper reports accuracy of 71.7 . Is it avg_acc: 66.29 or  Best test_Acc@1: 71.86 (epoch=44)?

**Comment by MingxuanXia** [comment]
The last epoch accuracy is 71.41 as shown in your results. 66.29 is the average class-wise accuracy which is totally a different metric.

**Comment by rst1991** [comment]
Thanks for the prompt response.

**Comment by MingxuanXia** [comment]
You are welcome.
